# 一、ndarray
### 1.ndarray的特性
### 多维性

In [2]:
import numpy as np

In [4]:
arr = np.array(5) # 创建0维的数组
print(arr)
print('arr的维度', arr.ndim)

5
arr的维度 0


In [14]:
arr = np.array([1,2,3]) # 创建1维的数组
print(arr)
print('arr的维度:', arr.ndim)

[1 2 3]
arr的维度: 1


In [13]:
arr = np.array([[1,2,3],[4,5,6]]) # 创建2维的数组
print(arr)
print('arr的维度:', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度: 2


### 同质性

In [16]:
arr = np.array([1,'hello']) # 不通类型的数据会被强制转换为同一种
print(arr)

['1' 'hello']


In [17]:
arr = np.array([1,1.25]) # 不通类型的数据会被强制转换为同一种
print(arr)

[1.   1.25]


### 2.ndarray的属性

In [28]:
arr = np.array(1)
print(arr)
print('数组的形状：',arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('数组的转置', arr.T)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
元素的数据类型： int64
数组的转置 1


In [38]:
arr = np.array([1,2.25,3])
print(arr)
print('数组的形状：',arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('数组的转置', arr.T)

[1.   2.25 3.  ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
元素的数据类型： float64
数组的转置 [1.   2.25 3.  ]


In [27]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print('数组的形状：',arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('数组的转置', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
元素的数据类型： int64
数组的转置 [[1 4]
 [2 5]
 [3 6]]


### 3.ndarray创建

#### zeros 全零数组，只需要指定数组形状

In [30]:
arr = np.zeros(2)
print(arr)

[0. 0.]


#### copy 拷贝，可修改拷贝后的数组，不影响远数组

arr1 = np.copy(arr)
print(arr1)
arr1[0]=8
print(arr1)
print(arr)

#### ones 全1数组, 可以使用dtype参数指定元素类型

In [36]:
arr2 = np.ones([2,3], dtype=float)
print(arr2)
print(arr2.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


#### full填充数组, 需要指定数组的形状和填充的数据

In [37]:
arr3 = np.full([2,3], 2026)
print(arr3)

[[2026 2026 2026]
 [2026 2026 2026]]


#### empty空数组，需要指定数组的形状，会随机生成元素

In [55]:
arr4 = np.empty([3,4], dtype=int)
print(arr4)

[[187605638254819               0 281472830540592 281472830541072]
 [281472830546512 281472830548832 281472830549152 281472830686288]
 [281472830687248 281472830690128 281472830778688 281472830800896]]


#### 以上方法的likes方法

In [56]:
# zeros_likes
arr5 = np.zeros_like(arr2)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
# ones_likes
arr6 = np.ones_like(arr)
print(arr6)

[1. 1.]


In [58]:
# empty_likes
arr7 = np.empty_like(arr3)
print(arr7)

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]


In [70]:
# full_likes
arr8 = np.full_like(arr5, 2027)
print(arr8)

[[2027. 2027. 2027.]
 [2027. 2027. 2027.]]


#### 等差数组，start，end，step

In [71]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


#### 等间隔数组，start，end，number

In [72]:
arr = np.linspace(1, 10, 2)
print(arr)

[ 1. 10.]


#### 对数等间隔数组，start，end，number，base=

In [73]:
arr = np.logspace(0, 4, 2,base=2)
print(arr)

[ 1. 16.]


#### 生成随机数组 

In [75]:
# 生成随机浮点数组
arr = np.random.rand(2,5)
print(arr)

[[0.64383995 0.51553624 0.77972915 0.25749191 0.1836979 ]
 [0.55651551 0.77277214 0.75238816 0.98368397 0.03764174]]


In [98]:
# 生成随机整数数组, 可以指定形状
arr = np.random.randint(1,6,(2,3))
print(arr)

[[5 4 3]
 [4 4 1]]


In [103]:
# 单位矩阵，对角线上元素为1，其他都为0
arr = np.eye(2,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


In [110]:
# 对角矩阵，主对角线的元素非零，其他元素为0，需要指定主对角线上的值
arr = np.diag([1,3,2,3])
print(arr)

[[1 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [108]:
# 生成正态分布数组（两边少，中间数多）中间数0到1之间
arr = np.random.randn(2,3)
print(arr)

[[-0.92959531 -0.16776968 -0.3724871 ]
 [-0.23594527  1.1085886   0.12832541]]


In [144]:
# 设置随机种子，当种子相同时，生成的随机数一致
np.random.seed(21)
arr = np.random.randint(1,20, (2, 3))
print(arr)

[[10 16  5]
 [17 17  4]]


### 4.ndarray元素类型
##### bool 布尔
##### int uint 整型
##### float 浮点
##### complex 复数

In [28]:
arr = np.array([1,0,0,3,5],dtype='bool')
print('布尔类型：',arr)

arr = np.array([-127, 0, 3, 127], dtype=np.int8)
print('8位整型：', arr)

arr = np.array([1, 0, 3, 255], dtype=np.uint8)
print('8位无符号整型：', arr)

arr = np.array([-3,2,145,67], dtype=np.float32)
print('32位单精度：', arr)

arr = np.array([-1, 0, 9 ,32], dtype=np.double)
print('双精度：', arr)

arr = np.array([-3, 9, 6, 31], dtype=np.complex64)
print('64位复数：', arr)

布尔类型： [ True False False  True  True]
8位整型： [-127    0    3  127]
8位无符号整型： [  1   0   3 255]
32位单精度： [ -3.   2. 145.  67.]
双精度： [-1.  0.  9. 32.]
64位复数： [-3.+0.j  9.+0.j  6.+0.j 31.+0.j]


### 5.数组的索引与切片

#### 一维数组的索引与切片

In [35]:
arr = np.array([10,2,3,45,75,132,43,66,45,77,89,65,90,34])
print('所有元素：',arr[:])
print('左闭右开区间：', arr[2:5])
print('slice切片，指定步长:', arr[slice(2,10,2)])
print('布尔运算取值：', arr[ (arr>2) & (arr < 70) ])

所有元素： [ 10   2   3  45  75 132  43  66  45  77  89  65  90  34]
左闭右开区间： [ 3 45 75]
slice切片，指定步长: [ 3 75 43 45]
布尔运算取值： [10  3 45 43 66 45 65 34]


#### 二维数组的索引与切片

In [74]:
arr = np.random.randint(4,10, (4,8))
print('输出所有元素：', arr[:])
print('指定元素索引：', arr[0,1])
print('指定第二行：', arr[1,:])
print('指定第三列：', arr[:,3])
print('对第二行的元素进行布尔筛选：', arr[1][ arr[1] > 4 ])
print('对第三列的元素进行布尔筛选', arr[:,3][ arr[:,3] > 5 ])

输出所有元素： [[4 7 6 8 7 5 9 4]
 [5 8 8 8 4 6 6 5]
 [6 9 5 4 4 9 8 6]
 [8 9 4 5 6 4 5 7]]
指定元素索引： 7
指定第二行： [5 8 8 8 4 6 6 5]
指定第三列： [8 8 4 5]
对第二行的元素进行布尔筛选： [5 8 8 8 6 6 5]
对第三列的元素进行布尔筛选 [8 8]


### 6 ndarray的运算

#### 一维数组的运算

In [76]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('加法：', a + b)
print('减法：', b - a)
print('除法：', a / b)
print('乘法：', a * b)

加法： [5 7 9]
减法： [3 3 3]
除法： [0.25 0.4  0.5 ]
乘法： [ 4 10 18]


#### 二维数组的运算, 相同下标位置上的数据运算

In [101]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print('加法：', a + b)
print('减法：', b - a)
print('除法：', a / b)
print('乘法：', a * b)

加法： [[ 8 10 12]
 [14 16 18]]
减法： [[6 6 6]
 [6 6 6]]
除法： [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
乘法： [[ 7 16 27]
 [40 55 72]]


#### 数组的广播机制，不同行列的数组，满足广播机制也可以运算

In [118]:
a = np.array([1,2,3])  # 1行3列
b = np.array([[4], [5], [6]])  # 3行1列
'''
a 广播后的数组
1 2 3
1 2 3
1 2 3
b 广播后的数组
4 4 4
5 5 5 
6 6 6
'''
print('加法：', a + b)
print('减法：', b - a)
print('除法：', a / b)
print('乘法：', a * b)

c = np.array([1,2,3]) # 1行3列
d = np.array([[4,5]]) # 1行2列
'''
c 和 d 无法广播，强行运算就会报错
'''
print('加法：', c + d)

加法： [[5 6 7]
 [6 7 8]
 [7 8 9]]
减法： [[3 2 1]
 [4 3 2]
 [5 4 3]]
除法： [[0.25       0.5        0.75      ]
 [0.2        0.4        0.6       ]
 [0.16666667 0.33333333 0.5       ]]
乘法： [[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


ValueError: operands could not be broadcast together with shapes (3,) (1,2) 

#### 矩阵的运算, 使用@符号

In [119]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3*3矩阵
b = np.array([[10,11,12], [13,14,15], [16,17,18]])
print(a @ b)
''' 
矩阵的运算规则，用a 行 * b 列，然后求和，放入对应的位置
a[0,:] [1 2 3]
b[:,0] [10 13 16]
结果 [0,0] 1*10 +2*13 +3*16 = 10+26+48=84
'''

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


' \n矩阵的运算规则，用a 行 * b 列，然后求和，放入对应的位置\na[0,:] [1 2 3]\nb[:,0] [10 13 16]\n结果 [0,0] 1*10 +2*13 +3*16 = 10+26+48=84\n'